<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="01 - Presentation Layer\" />
    <Folder Include="02 - Service Layer\" />
    <Folder Include="03 - Business Logic Layer\" />
    <Folder Include="04 - Business Entity\" />
    <Folder Include="05 - Data Access Layer\" />
  </ItemGroup>

</Project>