<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\04 - Business Entity\BE\BE.csproj" />
    <ProjectReference Include="..\..\03 - Business Logic Layer\BLL\BLL.csproj" />
    <ProjectReference Include="..\..\02 - Service Layer\Services\Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Login\" />
    <Folder Include="Profile\" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>UI</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>